#!/bin/bash

if [ -z "$1" ]
then
    echo "Please provide scriptname"
    exit 1;
fi

SCRIPT_FOLDER="$HOME/scripts"
SCRIPT_FILE="$SCRIPT_FOLDER/$1"

if [[ -f $SCRIPT_FILE ]]; then
    nvim $SCRIPT_FILE
else
    echo '#!/bin/bash' > $SCRIPT_FILE
    chmod +x $SCRIPT_FILE
    nvim $SCRIPT_FILE
fi
